name: AISettingsData
type: class
inherits: Asset

constructors:
  -
    description: Creates a new AISettingsData frostbite instance.
  -
    description: Creates a new AISettingsData frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type Asset to AISettingsData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: Asset
        description: The instance to cast to AISettingsData.
  -
    description: Casts an instance of type DataContainer to AISettingsData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to AISettingsData.

properties:
  soundEnvironmentConstants:
    type: SoundEnvironmentConstantData
    nullable: true
  coverConstants:
    type: CoverConstantData
    nullable: true
  decisionConstants:
    type: DecisionConstantData
    nullable: true
  positionEvaluationConstants:
    type: PositionEvaluationConstantData
    nullable: true
  timingConstants:
    type: TimingConstantData
    nullable: true
  debugConstants:
    type: DebugConstantData
    nullable: true
  readinessLevels:
    type: ReadinessLevels
  defaultBehaviourTemplate:
    type: BehaviourTemplateData
    nullable: true
  defaultVehicleType:
    type: AIVehicleBehaviourData
    nullable: true

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the AISettingsData type.

