name: BotPriorityConfigData
type: class
inherits: DataContainer

constructors:
  -
    description: Creates a new BotPriorityConfigData frostbite instance.
  -
    description: Creates a new BotPriorityConfigData frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type DataContainer to BotPriorityConfigData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to BotPriorityConfigData.

properties:
  debugColor:
    type: Vec3
  distance:
    type: float
  period:
    type: int
  angleOffset:
    type: float
  appliesToExecution:
    type: bool
  appliesToDecisions:
    type: bool

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the BotPriorityConfigData type.

