name: CombustionEngineConfigData
type: class
inherits: EngineConfigData

constructors:
  -
    description: Creates a new CombustionEngineConfigData frostbite instance.
  -
    description: Creates a new CombustionEngineConfigData frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type EngineConfigData to CombustionEngineConfigData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: EngineConfigData
        description: The instance to cast to CombustionEngineConfigData.
  -
    description: Casts an instance of type DataContainer to CombustionEngineConfigData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to CombustionEngineConfigData.

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the CombustionEngineConfigData type.

