name: CoreSettings
type: class

constructors:
  -
    description: Creates a new CoreSettings frostbite instance.
  -
    description: Creates a new CoreSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.

properties:
  randomTickSeed:
    type: int
  availableLanguages:
    type: string
  randomSessionId:
    type: int
  randomTimeSeed:
    type: int
  hardwareGpuBias:
    type: float
  hardwareProfile:
    type: HardwareProfile
  jobProcessorCount:
    type: int
  maxJobThreadCount:
    type: int
  host:
    type: string
  hostUser:
    type: string
  hostUserDomain:
    type: string
  initSeed:
    type: string
  logLevel:
    type: CoreLogLevel
  hardwareCpuBias:
    type: float
  gameConfigurationName:
    type: string
  profileDirectoryName:
    type: string
  displayAsserts:
    type: bool
  liveEditingEnable:
    type: bool
  useStorageServer:
    type: bool
  useDiskCaching:
    type: bool
  crashOnFatalErrors:
    type: bool

methods:
  -
    name: Clone
    description: Creates a shallow-copy clone of this structure, which is essentially the equivalent of creating a new structure of the same type and assigning the values of this structure to all of its properties. Any properties that contain structure types (eg. Vec3) will be cloned when assigning, while properties that contain instance types (eg. DataContainer) will be referencing the same instance.
    returns:
      type: CoreSettings
      description: The newly created structure.

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the CoreSettings type.

