name: DecalSettings
type: class
inherits: SystemSettings

constructors:
  -
    description: Creates a new DecalSettings frostbite instance.
  -
    description: Creates a new DecalSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type SystemSettings to DecalSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: SystemSettings
        description: The instance to cast to DecalSettings.
  -
    description: Casts an instance of type DataContainer to DecalSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to DecalSettings.

properties:
  staticBufferMaxVertexCount:
    type: int
  ringBufferMaxVertexCount:
    type: int
  drawEnable:
    type: bool
  systemEnable2:
    type: bool
  systemEnable:
    type: bool
  enable:
    type: bool
  debugMemUsageEnable:
    type: bool
  debugWarningsEnable:
    type: bool
  nvidiaStreamOutputWorkaroundEnable:
    type: bool

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the DecalSettings type.

