name: EqualizerSettings
type: class
inherits: DataContainer

constructors:
  -
    description: Creates a new EqualizerSettings frostbite instance.
  -
    description: Creates a new EqualizerSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type DataContainer to EqualizerSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to EqualizerSettings.

properties:
  lowShelfFrequency:
    type: float
  lowShelfGain:
    type: float
  highShelfFrequency:
    type: float
  highShelfGain:
    type: float
  hpCutoffFrequency:
    type: float

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the EqualizerSettings type.

