name: LicenseConfiguration
type: class
inherits: Asset

constructors:
  -
    description: Creates a new LicenseConfiguration frostbite instance.
  -
    description: Creates a new LicenseConfiguration frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type Asset to LicenseConfiguration. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: Asset
        description: The instance to cast to LicenseConfiguration.
  -
    description: Casts an instance of type DataContainer to LicenseConfiguration. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to LicenseConfiguration.

properties:
  licenses:
    type: LicenseInfo
    array: true

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the LicenseConfiguration type.

