name: LogicVisualEnvironmentEntityData
type: class
inherits: EntityData

constructors:
  -
    description: Creates a new LogicVisualEnvironmentEntityData frostbite instance.
  -
    description: Creates a new LogicVisualEnvironmentEntityData frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type EntityData to LogicVisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: EntityData
        description: The instance to cast to LogicVisualEnvironmentEntityData.
  -
    description: Casts an instance of type GameObjectData to LogicVisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: GameObjectData
        description: The instance to cast to LogicVisualEnvironmentEntityData.
  -
    description: Casts an instance of type GameDataContainer to LogicVisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: GameDataContainer
        description: The instance to cast to LogicVisualEnvironmentEntityData.
  -
    description: Casts an instance of type DataContainer to LogicVisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to LogicVisualEnvironmentEntityData.

properties:
  visualEnvironment:
    type: VisualEnvironmentBlueprint
    nullable: true
  visibility:
    type: float

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the LogicVisualEnvironmentEntityData type.

