name: MaterialSoldierSoundSettings
type: class
inherits: DataContainer

constructors:
  -
    description: Creates a new MaterialSoldierSoundSettings frostbite instance.
  -
    description: Creates a new MaterialSoldierSoundSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type DataContainer to MaterialSoldierSoundSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to MaterialSoldierSoundSettings.

properties:
  footStepSound:
    type: SoundAsset
    nullable: true
  proneSound:
    type: SoundAsset
    nullable: true
  landSound:
    type: SoundAsset
    nullable: true

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the MaterialSoldierSoundSettings type.

