name: MinMaxValueSelectorEntry
type: class
inherits: AudioGraphNodePortGroup

constructors:
  -
    description: Creates a new MinMaxValueSelectorEntry frostbite instance.
  -
    description: Creates a new MinMaxValueSelectorEntry frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type AudioGraphNodePortGroup to MinMaxValueSelectorEntry. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: AudioGraphNodePortGroup
        description: The instance to cast to MinMaxValueSelectorEntry.
  -
    description: Casts an instance of type DataContainer to MinMaxValueSelectorEntry. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to MinMaxValueSelectorEntry.

properties:
  input:
    type: AudioGraphNodePort

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the MinMaxValueSelectorEntry type.

