name: OcclusionSettings
type: class
inherits: DataContainer

constructors:
  -
    description: Creates a new OcclusionSettings frostbite instance.
  -
    description: Creates a new OcclusionSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type DataContainer to OcclusionSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to OcclusionSettings.

properties:
  enable:
    type: bool
  drawZbuffer:
    type: bool
  drawBinaryBuffer:
    type: bool

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the OcclusionSettings type.

