name: OnlineEnvironmentConsoleUrl
type: class

constructors:
  -
    description: Creates a new OnlineEnvironmentConsoleUrl frostbite instance.
  -
    description: Creates a new OnlineEnvironmentConsoleUrl frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.

properties:
  urls:
    type: OnlineEnvironmentConsoleUrlData
    array: true

methods:
  -
    name: Clone
    description: Creates a shallow-copy clone of this structure, which is essentially the equivalent of creating a new structure of the same type and assigning the values of this structure to all of its properties. Any properties that contain structure types (eg. Vec3) will be cloned when assigning, while properties that contain instance types (eg. DataContainer) will be referencing the same instance.
    returns:
      type: OnlineEnvironmentConsoleUrl
      description: The newly created structure.

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the OnlineEnvironmentConsoleUrl type.

