name: PresenceGameConfigurationServiceData
type: class
inherits: PresenceServiceData

constructors:
  -
    description: Creates a new PresenceGameConfigurationServiceData frostbite instance.
  -
    description: Creates a new PresenceGameConfigurationServiceData frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type PresenceServiceData to PresenceGameConfigurationServiceData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: PresenceServiceData
        description: The instance to cast to PresenceGameConfigurationServiceData.
  -
    description: Casts an instance of type Asset to PresenceGameConfigurationServiceData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: Asset
        description: The instance to cast to PresenceGameConfigurationServiceData.
  -
    description: Casts an instance of type DataContainer to PresenceGameConfigurationServiceData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to PresenceGameConfigurationServiceData.

properties:
  configUrl:
    type: OnlineEnvironmentConsoleUrl

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the PresenceGameConfigurationServiceData type.

