name: SettingsBundleAsset
type: class
inherits: Asset

constructors:
  -
    description: Creates a new SettingsBundleAsset frostbite instance.
  -
    description: Creates a new SettingsBundleAsset frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type Asset to SettingsBundleAsset. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: Asset
        description: The instance to cast to SettingsBundleAsset.
  -
    description: Casts an instance of type DataContainer to SettingsBundleAsset. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to SettingsBundleAsset.

properties:
  settings:
    type: SystemSettings
    array: true

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the SettingsBundleAsset type.

