name: SoundPatchConfigurationAssetEntry
type: class
inherits: SoundPatchConfigurationEntry

constructors:
  -
    description: Creates a new SoundPatchConfigurationAssetEntry frostbite instance.
  -
    description: Creates a new SoundPatchConfigurationAssetEntry frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type SoundPatchConfigurationEntry to SoundPatchConfigurationAssetEntry. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: SoundPatchConfigurationEntry
        description: The instance to cast to SoundPatchConfigurationAssetEntry.
  -
    description: Casts an instance of type DataContainer to SoundPatchConfigurationAssetEntry. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to SoundPatchConfigurationAssetEntry.

properties:
  nameHash:
    type: int
  value:
    type: Asset
    nullable: true

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the SoundPatchConfigurationAssetEntry type.

