name: SoundSettings
type: class
inherits: SystemSettings

constructors:
  -
    description: Creates a new SoundSettings frostbite instance.
  -
    description: Creates a new SoundSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type SystemSettings to SoundSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: SystemSettings
        description: The instance to cast to SoundSettings.
  -
    description: Casts an instance of type DataContainer to SoundSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to SoundSettings.

properties:
  voEnglish:
    type: string
  audioSystemUri:
    type: string
  voCommon:
    type: string
  voItalian:
    type: string
  voSpanish:
    type: string
  voFrench:
    type: string
  voGerman:
    type: string
  enable:
    type: bool

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the SoundSettings type.

