name: SoundEnvironmentConstantData
type: class
inherits: Asset

constructors:
  -
    description: Creates a new SoundEnvironmentConstantData frostbite instance.
  -
    description: Creates a new SoundEnvironmentConstantData frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type Asset to SoundEnvironmentConstantData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: Asset
        description: The instance to cast to SoundEnvironmentConstantData.
  -
    description: Casts an instance of type DataContainer to SoundEnvironmentConstantData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to SoundEnvironmentConstantData.

properties:
  humanPlayerSoldierMovementVolumeOverride:
    type: float
  memoryTime:
    type: float
  minimumLoudness:
    type: float

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the SoundEnvironmentConstantData type.

