name: SoundPatchConfigurationParameterEntry
type: class
inherits: SoundPatchConfigurationEntry

constructors:
  -
    description: Creates a new SoundPatchConfigurationParameterEntry frostbite instance.
  -
    description: Creates a new SoundPatchConfigurationParameterEntry frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type SoundPatchConfigurationEntry to SoundPatchConfigurationParameterEntry. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: SoundPatchConfigurationEntry
        description: The instance to cast to SoundPatchConfigurationParameterEntry.
  -
    description: Casts an instance of type DataContainer to SoundPatchConfigurationParameterEntry. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to SoundPatchConfigurationParameterEntry.

properties:
  nameHash:
    type: int
  value:
    type: float

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the SoundPatchConfigurationParameterEntry type.

