name: StatSpamSettings
type: class
inherits: Asset

constructors:
  -
    description: Creates a new StatSpamSettings frostbite instance.
  -
    description: Creates a new StatSpamSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type Asset to StatSpamSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: Asset
        description: The instance to cast to StatSpamSettings.
  -
    description: Casts an instance of type DataContainer to StatSpamSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to StatSpamSettings.

properties:
  spamList:
    type: StatSpamSetting
    array: true

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the StatSpamSettings type.

