name: StaticConfigAsset
type: class
inherits: Asset

constructors:
  -
    description: Creates a new StaticConfigAsset frostbite instance.
  -
    description: Creates a new StaticConfigAsset frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type Asset to StaticConfigAsset. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: Asset
        description: The instance to cast to StaticConfigAsset.
  -
    description: Casts an instance of type DataContainer to StaticConfigAsset. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to StaticConfigAsset.

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the StaticConfigAsset type.

