name: SyncedBFSettings
type: class
inherits: SystemSettings

constructors:
  -
    description: Creates a new SyncedBFSettings frostbite instance.
  -
    description: Creates a new SyncedBFSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type SystemSettings to SyncedBFSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: SystemSettings
        description: The instance to cast to SyncedBFSettings.
  -
    description: Casts an instance of type DataContainer to SyncedBFSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to SyncedBFSettings.

properties:
  gameModeCounterModifier:
    type: float
  unlicensedUnlocksUnlocked:
    type: bool
  noMinimap:
    type: bool
  noHud:
    type: bool
  noMinimapSpotting:
    type: bool
  no3dSpotting:
    type: bool
  noNameTag:
    type: bool
  onlySquadLeaderSpawn:
    type: bool
  teamSwitchingAllowed:
    type: bool
  memoryDefragUI:
    type: bool
  memoryGarbageCollectHavok:
    type: bool
  memoryDefragGlobal:
    type: bool
  allUnlocksUnlocked:
    type: bool

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the SyncedBFSettings type.

