name: VeniceUIConfiguration
type: class
inherits: Asset

constructors:
  -
    description: Creates a new VeniceUIConfiguration frostbite instance.
  -
    description: Creates a new VeniceUIConfiguration frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type Asset to VeniceUIConfiguration. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: Asset
        description: The instance to cast to VeniceUIConfiguration.
  -
    description: Casts an instance of type DataContainer to VeniceUIConfiguration. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to VeniceUIConfiguration.

properties:
  metaDataAssetPath:
    type: string

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the VeniceUIConfiguration type.

