name: VisualEnvironmentEntityData
type: class
inherits: GameEntityData

constructors:
  -
    description: Creates a new VisualEnvironmentEntityData frostbite instance.
  -
    description: Creates a new VisualEnvironmentEntityData frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type GameEntityData to VisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: GameEntityData
        description: The instance to cast to VisualEnvironmentEntityData.
  -
    description: Casts an instance of type SpatialEntityData to VisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: SpatialEntityData
        description: The instance to cast to VisualEnvironmentEntityData.
  -
    description: Casts an instance of type EntityData to VisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: EntityData
        description: The instance to cast to VisualEnvironmentEntityData.
  -
    description: Casts an instance of type GameObjectData to VisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: GameObjectData
        description: The instance to cast to VisualEnvironmentEntityData.
  -
    description: Casts an instance of type GameDataContainer to VisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: GameDataContainer
        description: The instance to cast to VisualEnvironmentEntityData.
  -
    description: Casts an instance of type DataContainer to VisualEnvironmentEntityData. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to VisualEnvironmentEntityData.

properties:
  visibility:
    type: float
  priority:
    type: int

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the VisualEnvironmentEntityData type.

