name: WeaponAnimationConfigurationModifier
type: class
inherits: WeaponModifierBase

constructors:
  -
    description: Creates a new WeaponAnimationConfigurationModifier frostbite instance.
  -
    description: Creates a new WeaponAnimationConfigurationModifier frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type WeaponModifierBase to WeaponAnimationConfigurationModifier. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: WeaponModifierBase
        description: The instance to cast to WeaponAnimationConfigurationModifier.
  -
    description: Casts an instance of type DataContainer to WeaponAnimationConfigurationModifier. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to WeaponAnimationConfigurationModifier.

properties:
  zoomInOutMeshTransitionFactors:
    type: float
    array: true
  animationConfiguration:
    type: AnimationConfigurationData
  animatedFireType:
    type: AnimatedFireEnum

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the WeaponAnimationConfigurationModifier type.

