name: WorldPartInclusionSettings
type: class
inherits: SubWorldInclusionSettings

constructors:
  -
    description: Creates a new WorldPartInclusionSettings frostbite instance.
  -
    description: Creates a new WorldPartInclusionSettings frostbite instance and assigns it the provided Guid.
    params:
      guid:
        type: Guid
        description: The Guid to assign to the newly created instance.
  -
    description: Casts an instance of type SubWorldInclusionSettings to WorldPartInclusionSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: SubWorldInclusionSettings
        description: The instance to cast to WorldPartInclusionSettings.
  -
    description: Casts an instance of type DataContainer to WorldPartInclusionSettings. Will throw an error when trying to cast from an unsupported type.
    params:
      other:
        type: DataContainer
        description: The instance to cast to WorldPartInclusionSettings.

static:
  typeInfo:
    type: TypeInformation
    description: The type information for the WorldPartInclusionSettings type.

